### ISSUE TITLE
TAS-19: Implement Hitbox For Player Model

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#11]
### TAS-19:
Implement hitbox mechanics for player boats so that the player model does not pass through tiles that should be impassable. This feature is dependent on #7, #2 , and an existing map. The hitbox will most likely be used in later features such as detecting if the player is near a key location or tile in order to interact with it

- [ ] Implement a hitbox surrounding the player model
- [ ] Implement collision detection for tiles

### DoD:

- [ ] Moving the player model into an impassable tile should be impossible
- [ ] The hitbox should detect which tiles the player model is covering

**Comment by willayy** [comment]
@adamkvarnsund @0-Gixty-0 As my work on #52 overlaps this TAS a lot i suggest we close this TAS?

**Comment by adamkvarnsund** [comment]
I agree, not so efficient if we both work on the same task

**Comment by willayy** [comment]
Finished by #52
