### ISSUE TITLE
Deciding where the player boat should spawn on map (AdvancedMapGenerator)

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#119]
### Because
We need to decide how we want the player boat to spawn. Because of the randomness of the implementation of the class AdvancedMapGenerator, we will need some kind of loop or algorithm to find water so that the boat always spawns in the water and not on an island.

**Comment by willayy** [comment]
There is an us for this so will close this discussion!
