### ISSUE TITLE
US-69: Implement smart entity spawning in Application

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#122]
As a user I want all entities to spawn on individual water tiles

### Because
Entities should only be spawned on their own separate water tiles because it makes the game both playable and realistic.

### Tasks
- [ ] Create a method that chooses a random location on the map that is possible
- [ ] Make it possible to spawn entities on possible positions

### Acceptance criteria
No individual entity spawns on an island tile or on top of another entity.

**Comment by willayy** [comment]
This is both a bug fix and an enhancement US depending on how you view it. Just clarifying why it has two labels.

**Comment by willayy** [comment]
Just clarifying that where the player spawn shouldnt be handled by the MapGenerator as the title kind of suggests.
