### ISSUE TITLE
TAS-21: Implement World Generation For Terrain Types

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#13]
### TAS-21:
Implement into the world generation different types of terrain. This task is heavily dependent on #12 and current world generation methods. **Therefore I am leaving this task open for later discussion**

**Comment by willayy** [comment]
@0-Gixty-0 Does different types of terrain mean different types of LandTile and SeaTile? I dont understand.

**Comment by willayy** [comment]
As this TAS has been implemented through other user stories i will close this issue
