### ISSUE TITLE
Projectile module problems

### ISSUE THREAD

**Issue by cavassi** [0-Gixty-0/Grupp-11-OOPP#138]
The class ABody implements the interface IDamagable, but every body can't take damage. For example, a projectile, which is a body, should not be able to take damage. But as implemented now, every body should be able to take damage.

The current solution is giving the projectile 100 hitpoints.

Projectile uses move, and doesn't check if body is out of the map. Right now I'm catching exception errors to solve it which is not ideal,

This should be discussed further in the group. This raises the question about what a projectile should be,

**Comment by willayy** [comment]
We should look at implementing the movement utility check in the movable body class instead of the entity class.
