### ISSUE TITLE
Decide how we should test methods containing objects

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#142]
### Because
We need to decide how we should test for example the generator of the entity matrix.

If we for example test with concrete ship objects, then the tests will fail if that class is taken away. We could test higher up in the hierarchy to make it more robust.

**Comment by willayy** [comment]
As we discussed yesterday the ideal way to do this is by testing with a small concrete inner class implementation, good spot finding this problem.
