### ISSUE TITLE
TAS-23: Implement Tile Module

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#15]
### TAS-23:
Implement Tile module according to UML diagram. I suggest the following order of implementation:

- [x] Implement Abstract class "ADrawable"
- [x] Implement Abstract class "ATile"
- [x] Implement class "LandTile"
- [x] Implement class "SeaTile"

### DoD:

- [x] It is possible to construct objects of type ATile
- [x] All methods in the hierarchy are tested.

**Comment by adamkvarnsund** [comment]
Deleted implementation of ADrawable and put it into a separate task together with the Position class

**Comment by adamkvarnsund** [comment]
No abstract methods in ATile that are needed to be overridden, that point in the DoD is removed

**Comment by willayy** [comment]
Closing this issue as its developement branch is merged and the problem no longer exists.
