### ISSUE TITLE
TAS-24: Implement Basic Map Generation

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#16]
### TAS-24:
Implement basic map generation according to the UML diagram. Basic generation meaning that it should be barebones and simply generate a map consisting of Tiles in a certain order. I suggest the following order of implementation:

- [x] Implement abstract class "AWorldGenerator"
- [x] Implement abstract class "AMapGenerator"
- [x] Implement class "Map"
- [x] implement class "World" 
- [x] implement class "BasicWorldGeneration"
- [x] implement class "BasicMapGeneration"

### DoD:

- [x] It is possible to construct objects of type Map
- [x] it is possible to construct objects of type World
- [x] Objects of type Map should be composed of objects of type Tile
- [x] It is possible to construct objects of type Map through the WorldGenerator interface
- [x] A basic world can be generated

**Comment by willayy** [comment]
@0-Gixty-0 I cant finish this task because Tile class is not implemented at the time, should we change the DoD? Thinking about creating a new Issue with these points:

- Implement class World
- Implement abstract class AreaGenerator
- implement abstract class WorldGenerator
- implement class BasicWorldgenerator
- implement class BasicMapGenerator

So we can create a map for the view to show, it should not take long as the BasicMapGenerator algorithm will be very crude and basic.

**Comment by 0-Gixty-0** [comment]
@willayy @adamkvarnsund 
Adding Adam to the thread since this touches on his task.

I understand the issue at hand. I think the points you want to add are reasonable as long as you feel it can be completed under one task. I was thinking of splitting it up but it seems like quite a cohesive module with the listed implementations.

However, I think the AreaGenerator is outside of the scope for implementing basic map generation and should be removed from the DoD. However, I wasn't present when it was discussed how that class interacts with the others in this context. Also, how is it possible to construct objects of type Map when the Tile class hasn't been implemented? Might be best to switch to a different task until the Tile class has been implemented and then merge that into this branch once it hits master.

**Comment by willayy** [comment]
@0-Gixty-0 As we agreed on i will edit the task and add:
- implement abstract class WorldGenerator
- implement class BasicWorldgenerator
- implement class BasicMapGenerator

And tweak the DoD.
