### ISSUE TITLE
TAS-25: Implement Basic View Module

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#17]
### TAS-25:
Implement a basic view module that can display the map according to specifications obtained from the model. This should also be fairly simple so that other features can be integrated quickly. Essentially it should draw the map and the player. I suggest this order of implementation:

- [x] Implement class "AppWindow"
- [x] Implement class "GameWorld"
- [x] Implement class "GameEntities
- [ ] #22

### DoD:

- [x] Upon starting the program the map should be drawn to the screen
- [ ] #23

**Comment by 0-Gixty-0** [comment]
I believe that the connection to model and ability to draw the player to the screen is beyond the scope of this task. Considering that there does not exist a model or a player in the current state of the master branch.

**Comment by willayy** [comment]
@0-Gixty-0 will check the boxes here as i think they are completed, correct me if im wrong.
