### ISSUE TITLE
EntitySpawner Class Needs Method To Set Builder Class

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#179]
The director attribute in entity spawner can can be final, however it needs to be able to update the builder class it uses since the entity spawner needs to be able to construct enemies and players of different body types (classes).

I recommend creating a method in EntitySpawner that passes to the directors method.
```java
public void changeBuilder(IEntityBuilder builder) {
        this.builder = builder;
    }
```

**Comment by willayy** [comment]
Decided to fix this as I have some time to kill.
