### ISSUE TITLE
US-112: Add test fire at player to AiCommanderTest class

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#236]
As a developer i want to test that the AiCommander can fire at the player

### Because
Its an important part of the game and it should be tested
### Tasks

- [ ] Write testFireAtPlayer() test in AiCommanderTest  class.

### Acceptance criteria
The testFireAtPlayer test is written.

**Comment by 0-Gixty-0** [comment]
This issue already exists. See #204
