### ISSUE TITLE
TAS-10: Design Player Model

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#3]
### TAS-11:

- [x] #18
- [x] Design a clear player model ship that displays on the screen.

### DoD:
- [x] There is a player model that can be displayed on the screen.
- [x] There is a graphical component that users can use to differentiate their boat from other boats in the game. Can be verified through user feedback.

**Comment by DuchessMuhr** [comment]
För tillfället ser jag inte behovet av att ha en border/highlight på spelarens skepp

**Comment by 0-Gixty-0** [comment]
> För tillfället ser jag inte behovet av att ha en border/highlight på spelarens skepp

Jag tycker också att det rimligt att utelämna det kravet för denna task. I sådana fall så tänker jag att vi kan merga in den som skapats?
