### ISSUE TITLE
Renaming suggestions.

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#34]
@adamkvarnsund @cavassi @0-Gixty-0 @DuchessMuhr I suggest we rename:

~~- [x] view to View (Same as the other MVC modules)~~

- [x] Make all modules lower case to fit Java conventions.

- [x] AbstractViewTile to AViewTile (Same as the rest of the project)

- [x] Rename this to showGame as the actual game has been drawn and this really just shows it <br> https://github.com/0-Gixty-0/Grupp-11-OOPP/blob/bdc4b0b4cbb5b6507a8519b498bcc38740d5ca18/sailinggame/src/main/java/com/group11/view/AppWindow.java#L76

- [x] Renaming A Drawable in Model to A TextureIdentifiable (Not 100% happy please come with suggestions) because i think we can come up with a name that isnt project ambigous (same name means different things in different contexts).

- [x] Renaming A Drawable TEXTURE attribute to texture <br> https://github.com/0-Gixty-0/Grupp-11-OOPP/blob/f38613f5f1c73c80150af9fa7b00696f51fb755d/sailinggame/src/main/java/com/group11/Model/ADrawable.java#L4

Tagging everyone because anyone could fix/give input on this.

**Comment by 0-Gixty-0** [comment]
I'm not 100% happy with these changes. Specifically renaming the folder for the MVC. Lowercase is the convention and now I have 24 errors since the package imports didn't update along with renaming the folders. Granted the code still compiles and runs regardless if the import and actual name are the same (lowercase or uppercase). But 24 errors is not very good. I am going to refactor and make them lowercase again.

**Comment by willayy** [comment]
@0-Gixty-0 i agree thats why i changed the issue to all modules should be lowercase. The changes i originally pushed to main was all lowercase modules, i think the accidental push to main i did (thought i was on a branch) from my other computer accidentally reverted it to uppercase which was not my intention.

**Comment by willayy** [comment]
@0-Gixty-0 The strange thing is that my local copy of main has all lowercase and says its up to date so thats a bit worrying.

**Comment by 0-Gixty-0** [comment]
Discussed and closed on monday meeting
