### ISSUE TITLE
Missing testclasses for View and Model modules.

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#36]
@adamkvarnsund @cavassi @0-Gixty-0 @DuchessMuhr

Our workflow from the group-contract states that all classes should have a testclass and that all public methods should have a test. This includes things like getters, setters and public view methods. If you regard a method not testable (Drawing shapes on the screen) leave the test empty and write a comment describing why its empty.

It might seem like unnecessary work here is why i think it isnt:

-  It avoids confusion about why some classes have testclasses and some classed dont.
-  Consistency creates less room for error.
-  It has no drawbacks, if you think something doesnt deserve a test just write that as a comment in the test.

- [ ] All classes in Module has a testclass, all public methods in each class has a test.
- [ ] All classes in View has a testclass, all public methods in each class has a test.

**Comment by willayy** [comment]
@adamkvarnsund @cavassi @0-Gixty-0 @DuchessMuhr Made a suggestion in the group contract to change Testing to only be done on implementations of abstract classes as our abstract classes right now are being tested with implementations.

**Comment by adamkvarnsund** [comment]
I created a separate issue for discussion the testing of abstract classes #63

**Comment by willayy** [comment]
This has been incorporated into #70
