### ISSUE TITLE
Errors in implementation of TAS-22

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#40]
@cavassi While reviewing the code pushed to main from the branch associated i found these errors that need correction:

- [x] Add branch to the issue
~~- [x] Add JavaDoc for SmallShip (comment the class)~~
~~- [x] Add JavaDoc for MedShip (comment the class)~~ 
~~- [x] Add javaDoc for LargeShip (comment the class)~~ 
~~- [ ] Add testClass for SmallShip~~
~~- [ ] Add testClass for MedShip~~
~~- [ ] Add testClass for LargeShip~~
~~- [ ] Testclass for AShip missing tests for all public methods~~
- [x] Int velocity should only be in AMovableBody (The UML diagram was wrong and had both AMovableBody and ABody have this attribute)
- [x] This should always be instantiated with velocity zero <br> https://github.com/0-Gixty-0/Grupp-11-OOPP/blob/1034b6ae7732e63c3b83b03a92381c3c3f02945c/sailinggame/src/main/java/com/group11/Model/AMovableBody.java#L19-L21
- [x] This should be removed<br> https://github.com/0-Gixty-0/Grupp-11-OOPP/blob/1034b6ae7732e63c3b83b03a92381c3c3f02945c/sailinggame/src/main/java/com/group11/Model/AShip.java#L27

**Comment by cavassi** [comment]
Removed the three classes SmallShip, MedShip, and LargeShip, and insted changed AShip from abstract to the concrete class Ship.
