### ISSUE TITLE
Documentation in README is inconsistent

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#49]
❗This issue is a reminder, no need to rush fixing this.

### What's wrong?
Currently the documentation in README is a bit inconsistent from US to US, for example I think there is some inconsistency about what "Why" means. Is it "Why did we make make this US" or is it "Why did I implement my classes/algorithms/solutions in the way I did".

### Solution
We should probably discuss in more depth what each sub-header of US documentation should be.

- [x] Discuss each sub-header of the US documentation and write a formal definition for them at a meeting.

**Comment by 0-Gixty-0** [comment]
Added this issue to the meeting agenda for Lv4

**Comment by willayy** [comment]
As this issue has been discussed and we agreed on a double check before the project deadline i deem this issue as closed.
