### ISSUE TITLE
Code duplication in ATile and ABody

### ISSUE THREAD

**Issue by willayy** [0-Gixty-0/Grupp-11-OOPP#59]
Both of these classes has Point Pos, this should and can be easily refactored into a common parent.

**Comment by willayy** [comment]
@adamkvarnsund Did you finish this task, i think we talked about it but i dont recall what we said.

**Comment by adamkvarnsund** [comment]
Almost done, just need to clean up the old implementations

**Comment by adamkvarnsund** [comment]
I solved this task #60
