### ISSUE TITLE
Decide how we should test abstract classes

### ISSUE THREAD

**Issue by adamkvarnsund** [0-Gixty-0/Grupp-11-OOPP#63]
### _**Suggestion:**_

My suggestion is that if the abstract class contains a lot of shared methods we should create a temporary concrete implementation for the abstract class and test that.

_**Why:**_

It makes it so that no test duplication is possible which also gives the test a lot more readability. 

_Example:_

https://github.com/0-Gixty-0/Grupp-11-OOPP/blob/20da7eb3c0318f227bf863a83ed913fac473f54a/sailinggame/src/test/java/ATileTest.java#L40-L44

**Comment by 0-Gixty-0** [comment]
I think this is a great idea! The concrete test class can be defined as a nested class in the test class for that specific abstract class. Easy and simple solution to the problem. Nice work.

**Comment by willayy** [comment]
Discussed at the meeting 20/11/2023 so I think this is done, leaving it up to @adamkvarnsund if this should be closed.
