### ISSUE TITLE
Code Duplication And Dependency Issues

### ISSUE THREAD

**Issue by 0-Gixty-0** [0-Gixty-0/Grupp-11-OOPP#81]
I have notices some issues in the codebase that should be discussed. 
### Issue 1
There is some code duplication in the classes PlayableEntity and UnplayableEntity. Their implementation of the interface ICommandable is the exact same and I see no reason that this will change in the future since their only purpose is to pass a parameter based on some logic to the body of the entity to actually perform the command. Since it is the body that performs the command and therefore has it's own implementation their shouldn't be any difference in the implementation of actually passing this command to the body. I feel like this is reflected in the fact that I removed the IAICommandable interface when implementing UnplayableEntity since it had no difference to the normal Commandable. Both playable and unplayable entities are commandable!

### Issue 2
PlayableEntity and UnplayableEntity are dependent on HasWeapon which is unnecessary. If they both need the dependency then it should be their superclass that has that dependency instead.

### Proposed Solution
I think we should remove the interface ICommandable and instead move those methods into defined methods in AMovableEntity. Since a movable entity can move it must also be commandable, or else it can't move. This however presents another issue. The methods interact and attack do not belong in a class defined by if their objects can move or not. I suggest we move all three methods into concrete implementations in the class AMovableEntity and then rename it to ACommandableEntity. This does not invalidate the subclasses of the hierarchy and makes the most sense name wise. We can then add LocationEntity as a subclass to ACommandableEntity and have the attribute "body" in ACommandableEntity be of ABody. This allows LocationEntity to have an ImmovableBody while the logic for checking if a command is to be passed down to a body is in the ACommandableEntity.

Think of the ACommandableEntity as a brain that takes in commands. The brain processes the command and reasons if it's body can perform the task it's been issued. Then passes that task to it's body. For example the "brain" of a guard tower receives the move command. It decides that it can't move and rejects the command (Because of being type Immovable). However it receives the attack command and decides that it can attack (because guard tower implements HasWeapon) and passes it to the body. On the other hand the brain of a merchant ship without cannons would make the reverse decisions.

### Notes
This is quite a large change in the codebase, however one I think is sort of necessary since it solves a lot of code smells at the same time and allows us to more easily extend the code. For example when working on #79 I needed to ctrl+c ctrl+v code...

**Comment by 0-Gixty-0** [comment]
@adamkvarnsund @cavassi @DuchessMuhr @willayy

**Comment by 0-Gixty-0** [comment]
I realized that in the current state of the code this means that there would be no code in the classes PlayableEntity and UnplayableEntity and that they then can be removed and later created when actually required by the code.

**Comment by cavassi** [comment]
I don't see any disadvantages with these changes. It removes code duplication and, as @0-Gixty-0 explained to me, makes it easy to use a builder pattern. I'm in favor for this.

**Comment by willayy** [comment]
Good idea @0-Gixty-0 I agree.
As we discussed this is the best way to move forward with the entity "subpackage" since its the solution with the most pro's and least cons. Well pass this by @ArthurAlexandersson this friday.

**Comment by DuchessMuhr** [comment]
I agree that this would be a good and, in the long run, a necessary change!

**Comment by 0-Gixty-0** [comment]
Thanks for the input and discussion. As we decided I will get to work on implementing this as a user story
